### ISSUE TITLE
Hardcoded mdl_ prefix in SQL queries

### ISSUE THREAD

**Issue by mudrd8mz** [devlionco/moodle-local_sharewith#2]
There seems to be the `mdl_` prefix hard-coded in two places in SQL queries. There must be no `mdl_context`, it should be replaced with `{context}`

**Comment by mudrd8mz** [comment]
This breaks the sharing functionality on sites that use an alternative DB prefix:

![image](https://user-images.githubusercontent.com/85831/70818525-3d7b8980-1dd4-11ea-8eb5-a37c9d798a5a.png)

**Comment by ilyaDymshits** [comment]
Done!
